DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS destination_likes;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS destinations;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(255) NOT NULL UNIQUE,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_roles (
	user_id BIGINT NOT NULL,
	roles VARCHAR(255) NOT NULL,
	PRIMARY KEY (user_id, roles),
	FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS destinations (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	location VARCHAR(255) NOT NULL,
	description VARCHAR(255) NOT NULL,
	image_url VARCHAR(255) NOT NULL,
	user_id BIGINT NOT NULL,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS reviews (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	rating DOUBLE NOT NULL,
	body VARCHAR(255) NOT NULL,
	user_id BIGINT NOT NULL,
	destination_id BIGINT NOT NULL,
	created_at TIMESTAMP NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(id),
	FOREIGN KEY (destination_id) REFERENCES destinations(id)
);

CREATE TABLE IF NOT EXISTS destination_likes (
	user_id BIGINT NOT NULL,
	destination_id BIGINT NOT NULL,
	PRIMARY KEY (user_id, destination_id),
	FOREIGN KEY (user_id) REFERENCES users(id),
	FOREIGN KEY (destination_id) REFERENCES destinations(id)
);

CREATE TABLE IF NOT EXISTS messages (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	content VARCHAR(255) NOT NULL,
	user_id BIGINT NOT NULL,
	room_id VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL,
	message_type VARCHAR(10),
	FOREIGN KEY (user_id) REFERENCES users(id)
);
